export const SITE_URL = 'https://naturalquill.one';

export interface Post {
  slug: string;
  title: string;
  description: string;
  published: string; // ISO date
  updated: string; // ISO date
  readTime: string;
}

// Single source of truth for the blog index, sitemap, homepage links, and article metadata.
export const POSTS: Post[] = [
  {
    slug: 'ai-words-to-avoid',
    title: 'AI Words to Avoid: ChatGPT Words and Phrases, With Plain Alternatives',
    description: 'The words and phrases that make writing sound like ChatGPT, from "delve" to "it is important to note", with a plain alternative for each.',
    published: '2026-10-05',
    updated: '2026-10-05',
    readTime: '9 min read',
  },
  {
    slug: 'how-to-humanize-chatgpt-text',
    title: 'How to Humanize ChatGPT Text for Free',
    description: 'The writing habits that make ChatGPT text easy to spot, and how to revise them so your draft sounds like a person wrote it.',
    published: '2026-04-26',
    updated: '2026-10-04',
    readTime: '5 min read',
  },
  {
    slug: 'how-to-make-chatgpt-essay-undetectable',
    title: 'How to Make a ChatGPT Essay Sound Natural',
    description: 'A step-by-step guide to revising a ChatGPT essay into clear, natural academic writing without losing your argument or citations.',
    published: '2026-04-26',
    updated: '2026-10-04',
    readTime: '6 min read',
  },
  {
    slug: 'how-to-make-ai-writing-undetectable',
    title: 'How to Make AI Writing Sound Natural',
    description: 'What AI detectors tend to measure, and how to revise AI-assisted drafts for natural rhythm, plain wording, and a real voice.',
    published: '2026-04-26',
    updated: '2026-10-04',
    readTime: '5 min read',
  },
  {
    slug: 'how-to-bypass-turnitin-ai-detection',
    title: 'How Turnitin Reads AI Writing Patterns',
    description: 'What Turnitin AI detection looks at and how to revise AI-assisted text for clearer, more natural academic writing.',
    published: '2026-04-26',
    updated: '2026-10-04',
    readTime: '5 min read',
  },
  {
    slug: 'how-to-bypass-gptzero',
    title: 'How GPTZero Reads AI Writing Patterns',
    description: 'What GPTZero measures, including perplexity and burstiness, and how to revise AI text so it reads clearer and less repetitive.',
    published: '2026-04-26',
    updated: '2026-10-04',
    readTime: '4 min read',
  },
  {
    slug: 'best-ai-humanizer-for-students',
    title: 'Best AI Humanizer for Students in 2026',
    description: 'What students should look for in an AI humanizer: meaning, citations, and academic tone kept intact, at a fair price.',
    published: '2026-04-26',
    updated: '2026-10-04',
    readTime: '5 min read',
  },
  {
    slug: 'best-ai-humanizer-2025',
    title: 'Best AI Humanizer Tools in 2026 (Honest Comparison)',
    description: 'AI humanizer tools compared on naturalness, writing quality, editing control, and price.',
    published: '2026-04-26',
    updated: '2026-10-04',
    readTime: '6 min read',
  },
];

export function getPost(slug: string): Post {
  const post = POSTS.find(p => p.slug === slug);
  if (!post) throw new Error(`Unknown post: ${slug}`);
  return post;
}

export function formatDate(iso: string): string {
  return new Date(`${iso}T00:00:00Z`).toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
    timeZone: 'UTC',
  });
}

/** Generated by app/opengraph-image.tsx. Pages that set their own openGraph must list it explicitly. */
export const OG_IMAGE = { url: '/opengraph-image', width: 1200, height: 630, alt: 'Natural Quill: turn AI drafts into natural, human writing' };
